git:
  branch: dev

target_port: 3000

wants:
  mongo: true

secrets:
  - GROUND_TRUTH_CLIENT_SECRET
  - GROUND_TRUTH_CLIENT_ID
  - SECRET

env:
  GROUND_TRUTH_URL: https://login.dev.hack.gt
  PORT: 3000
